name: Lint and test python code
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: python3 -m pip install --user flake8
      - run: python3 -m flake8 src/*.py -v
      - run: python3 -m doctest src/*.py -v
